# Generated by Django 5.2.11 on 2026-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Worker_chatroom',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='build_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
