# Generated by Django 5.2.11 on 2026-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Authentication_user',
                'managed': False,
            },
        ),
    ]
